#include "COMMANDES.h"

namespace NS_Composants
{
	COMMANDES::COMMANDES(void)
	{
		this->REF_COMMANDE = "RIEN";
		this->DATE_LIVRAISON_PREVUE = "RIEN";
		this->DATE_EMISSION_COMMANDE = "RIEN";
		this->DATE_SOLDE_REGLEMENT = "RIEN";
		this->MONTANT_HT = 0;
		this->MONTANT_TVA = 0;
		this->MONTANT_TTC = 0;
		this->DATE_EMISSION_FACTURE = "RIEN";
		this->ID_CLIENTC = -1;
	}
	String^ COMMANDES::SELECT(void)
	{
		return "SELECT COMMANDES.REF_COMMANDE, DATE_LIVRAISON_PREVUE, DATE_EMISSION_COMMANDE, DATE_SOLDE_REGLEMENT, MONTANT_HT, MONTANT_TVA, MONTANT_TTC, DATE_EMISSION_FACTURE, PAIEMENT.MONTANT_PAIEMENT, PAIEMENT.DATE_PAIEMENT, MODE_REGLEMENT.MODE_REGLEMENT, CONTENIR.QUANTITE_ARTICLE " +
			"FROM  COMMANDES  LEFT JOIN CLIENT ON COMMANDES.ID_CLIENT = CLIENT.ID_CLIENT " +
			"LEFT JOIN PAIEMENT ON COMMANDES.REF_COMMANDE = PAIEMENT.REF_COMMANDE " +
			"LEFT JOIN MODE_REGLEMENT ON PAIEMENT.ID_MODE = MODE_REGLEMENT.ID_MODE " +
			"LEFT JOIN CONTENIR ON COMMANDES.REF_COMMANDE = CONTENIR.REF_COMMANDE ";
	}

	String^ COMMANDES::SELECTCOMMANDE(void)
	{
		return "SELECT REF_COMMANDE, DATE_LIVRAISON_PREVUE, DATE_EMISSION_COMMANDE, DATE_SOLDE_REGLEMENT, MONTANT_HT, MONTANT_TVA, MONTANT_TTC, DATE_EMISSION_FACTURE ";


	}//

	String^ COMMANDES::INSERT(void)
	{
		return "INSERT INTO COMMANDES " +
			"(REF_COMMANDE, DATE_LIVRAISON_PREVUE, DATE_EMISSION_COMMANDE, DATE_SOLDE_REGLEMENT, MONTANT_HT, MONTANT_TVA, MONTANT_TTC, DATE_EMISSION_FACTURE) " +
			"VALUES('" + this->getREF_COMMANDE() + "','" + this->getDATE_LIVRAISON_PREVUE() + "', '" + this->getDATE_EMISSION_COMMANDE() + "', '" + this->getDATE_SOLDE_REGLEMENT() + "', '" + this->getMONTANT_HT() + "', '" + this->getMONTANT_TVA() + "', '" + this->getMONTANT_TTC() + "', '" + this->getDATE_EMISSION_FACTURE() + "');SELECT @@IDENTITY;";
	}
	String^ COMMANDES::UPDATE(void)
	{
		return "UPDATE COMMANDES " +
			"SET DATE_LIVRAISON_PREVUE = '" + this->getDATE_LIVRAISON_PREVUE() + "', DATE_EMISSION_COMMANDE = '" + this->getDATE_EMISSION_COMMANDE() + "', DATE_SOLDE_REGLEMENT'" + this->getDATE_SOLDE_REGLEMENT() + "', MONTANT_HT '" + this->getMONTANT_HT() + "', MONTANT_TVA'" + this->getMONTANT_TVA() + "', MONTANT_TTC'" + this->getMONTANT_TTC() + "', DATE_EMISSION_FACTURE'" + this->getDATE_EMISSION_FACTURE() + "' " +

			"WHERE(REF_COMMANDE = " + this->getREF_COMMANDE() + ");";
	}
	String^ COMMANDES::DELETE(void)
	{
		return "DELETE FROM COMMANDES " +
			"WHERE(REF_COMMANDE = " + this->getREF_COMMANDE() + ");";
	}
	void COMMANDES::setREF_COMMANDE(String^ REF_COMMANDE)
	{
		if (REF_COMMANDE != "")
		{
			this->REF_COMMANDE = REF_COMMANDE;
		}
	}
	void COMMANDES::setDATE_LIVRAISON_PREVUE(String^ DATE_LIVRAISON_PREVUE)
	{
		if (DATE_LIVRAISON_PREVUE != "")
		{
			this->DATE_LIVRAISON_PREVUE = DATE_LIVRAISON_PREVUE;
		}
	}
	void COMMANDES::setDATE_EMISSION_COMMANDE(String^ DATE_EMISSION_COMMANDE)
	{
		if (DATE_EMISSION_COMMANDE != "")
		{
			this->DATE_EMISSION_COMMANDE = DATE_EMISSION_COMMANDE;
		}
	}
	void COMMANDES::setDATE_SOLDE_REGLEMENT(String^ DATE_SOLDE_REGLEMENT)
	{
		if (DATE_SOLDE_REGLEMENT != "")
		{
			this->DATE_SOLDE_REGLEMENT = DATE_SOLDE_REGLEMENT;
		}
	}
	void COMMANDES::setMONTANT_HT(double MONTANT_HT)
	{
		if (MONTANT_HT > 0)
		{
			this->MONTANT_HT = MONTANT_HT;
		}
	}
	void COMMANDES::setMONTANT_TVA(double MONTANT_TVA)
	{
		if (MONTANT_TVA > 0)
		{
			this->MONTANT_TVA = MONTANT_TVA;
		}
	}
	void COMMANDES::setMONTANT_TTC(double MONTANT_TTC)
	{
		if (MONTANT_TTC > 0)
		{
			this->MONTANT_TTC = MONTANT_TTC;
		}
	}
	void COMMANDES::setDATE_EMISSION_FACTURE(String^ DATE_EMISSION_FACTURE)
	{
		if (DATE_EMISSION_FACTURE != "")
		{
			this->DATE_EMISSION_FACTURE = DATE_EMISSION_FACTURE;
		}
	}
	String^ COMMANDES::getREF_COMMANDE(void)
	{
		return this->REF_COMMANDE;
	}
	String^ COMMANDES::getDATE_LIVRAISON_PREVUE(void)
	{
		return this->DATE_LIVRAISON_PREVUE;
	}
	String^ COMMANDES::getDATE_EMISSION_COMMANDE(void)
	{
		return this->DATE_EMISSION_COMMANDE;
	}
	String^ COMMANDES::getDATE_SOLDE_REGLEMENT(void)
	{
		return this->DATE_SOLDE_REGLEMENT;
	}
	double COMMANDES::getMONTANT_HT(void)
	{
		return this->MONTANT_HT;
	}
	double COMMANDES::getMONTANT_TVA(void)
	{
		return this->MONTANT_TVA;
	}
	double COMMANDES::getMONTANT_TTC(void)
	{
		return this->MONTANT_TTC;
	}
	String^ COMMANDES::getDATE_EMISSION_FACTURE(void)
	{
		return this->DATE_EMISSION_FACTURE;
	}
	int COMMANDES::getID_CLIENTC(void)
	{

		return this->ID_CLIENTC = ID_CLIENTC;

	}
	void COMMANDES::setID_CLIENTC(int ID_CLIENTC)
	{
		if (ID_CLIENTC > 0)
		{
			this->ID_CLIENTC = ID_CLIENTC;
		}
	}
}