#include "PERSONNEL.h"
namespace NS_Composants
{
	PERSONNEL::PERSONNEL(void)
	{
		this->ID_PERSONNEL = -1;
		this->NOM_PERSONNEL = "RIEN";
		this->PRENOM_PERSONNEL = "RIEN";
		this->ADRESSE_MAIL_PERSONNEL = "RIEN";
		this->DATE_EMBAUCHE = "RIEN";
	}
	String^ PERSONNEL::SELECT(void)
	{
		return "SELECT ID_PERSONNEL, NOM_PERSONNEL, PRENOM_PERSONNEL, ADRESSE_MAIL_PERSONNEL, DATE_EMBAUCHE " +
			"FROM PERSONNEL;";
	}
	String^ PERSONNEL::SELECTPERSONNELADRESSE(void)
	{
		return "SELECT ID_PERSONNEL, NOM_PERSONNEL, PRENOM_PERSONNEL, ADRESSE_MAIL_PERSONNEL, DATE_EMBAUCHE, ADRESSE.RUE, ADRESSE.CODE_POSTAL, ADRESSE.VILLE " +
			"FROM dbo.PERSONNEL LEFT JOIN dbo.ADRESSE ON(dbo.PERSONNEL.ID_ADRESSE = ADRESSE.ID_ADRESSE)";
			
		/*"FROM dbo.CLIENT  LEFT JOIN dbo.ADRESSE AS ADRESSE_FAC ON(dbo.client.ID_CLIENT = ADRESSE_FAC.ID_CLIENT_FACTURATION) " +
			"LEFT JOIN dbo.ADRESSE AS ADRESSE_LIV ON(dbo.CLIENT.ID_CLIENT = ADRESSE_LIV.ID_CLIENT_LIVRAISON)";
		*/
			
	}
	String^ PERSONNEL::INSERT(void)
	{
		return "INSERT INTO PERSONNEL " +
			"(NOM_PERSONNEL, PRENOM_PERSONNEL, ADRESSE_MAIL_PERSONNEL, DATE_EMBAUCHE) " +
			"VALUES('" + this->getNOM_PERSONNEL() + "', '" + this->getPRENOM_PERSONNEL() + "', '" + this->getADRESSE_MAIL_PERSONNEL() + "', '" + this->getDATE_EMBAUCHE() + "');SELECT @@IDENTITY;";
	}
	String^ PERSONNEL::UPDATE(void)
	{
		return "UPDATE PERSONNEL " +
			"SET NOM_PERSONNEL = '" + this->getNOM_PERSONNEL() + "', PRENOM_PERSONNEL = '" + this->getPRENOM_PERSONNEL() + "', ADRESSE_MAIL_PERSONNEL'" + this->getADRESSE_MAIL_PERSONNEL() + "', DATE_EMBAUCHE '" + this->getDATE_EMBAUCHE() + "' " +

			"WHERE(ID_PERSONNEL = " + this->getID_PERSONNEL() + ");";
	}
	String^ PERSONNEL::DELETE(void)
	{
		return "DELETE FROM PERSONNEL " +
			"WHERE(ID_PERSONNEL = " + this->getID_PERSONNEL() + ");";
	}
	void PERSONNEL::setID_PERSONNEL(int ID_PERSONNEL)
	{
		if (ID_PERSONNEL > 0)
		{
			this->ID_PERSONNEL = ID_PERSONNEL;
		}
	}
	void PERSONNEL::setPRENOM_PERSONNEL(String^ PRENOM_PERSONNEL)
	{
		if (PRENOM_PERSONNEL != "")
		{
			this->PRENOM_PERSONNEL = PRENOM_PERSONNEL;
		}
	}
	void PERSONNEL::setNOM_PERSONNEL(String^ NOM_PERSONNEL)
	{
		if (NOM_PERSONNEL != "")
		{
			this->NOM_PERSONNEL = NOM_PERSONNEL;
		}
	}
	void PERSONNEL::setADRESSE_MAIL_PERSONNEL(String^ ADRESSE_MAIL_PERSONNEL)
	{
		if (ADRESSE_MAIL_PERSONNEL != "")
		{
			this->ADRESSE_MAIL_PERSONNEL = ADRESSE_MAIL_PERSONNEL;
		}
	}
	void PERSONNEL::setDATE_EMBAUCHE(String^ DATE_EMBAUCHE)
	{
		if (DATE_EMBAUCHE != "")
		{
			this->DATE_EMBAUCHE = DATE_EMBAUCHE;
		}
	}
	int PERSONNEL::getID_PERSONNEL(void)
	{
		return this->ID_PERSONNEL;
	}
	String^ PERSONNEL::getNOM_PERSONNEL(void)
	{
		return this->NOM_PERSONNEL;
	}
	String^ PERSONNEL::getPRENOM_PERSONNEL(void)
	{
		return this->PRENOM_PERSONNEL;
	}
	String^ PERSONNEL::getADRESSE_MAIL_PERSONNEL(void)
	{
		return this->ADRESSE_MAIL_PERSONNEL;
	}
	String^ PERSONNEL::getDATE_EMBAUCHE(void)
	{
		return this->DATE_EMBAUCHE;
	}
}